# Generated by Django 4.1.5 on 2023-01-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='DOB',
            field=models.TimeField(null=True),
        ),
    ]
