# Generated by Django 4.1.5 on 2023-01-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_custom_user_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custom_user',
            options={'verbose_name': 'Custom_User'},
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
